name: PyPI release
on: [push]

jobs:
  pypi_release:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run: python -m pip install --upgrade setuptools wheel twine
    - name: Build
      run: |
        python setup.py sdist bdist_wheel
        twine check dist/*
    - name: Publish package
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@v1.1.0
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
